language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install tox
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
deploy:
  provider: pypi
  user: joshmarshall
  password:
    secure: BcVdtpGqpLeZTYlVHeutQRkTyO6pQawUCXy7J8bHb3RH/gwb0H0Gt66HmAhPKLDGFQmJTsqI+d3w9jEOGSyn1b9zvP40lZpY60jJFfRbVzm/M2Z15M+BUbDMwn48LuZHfA0tfloFfXqdYGKdGkdgIhdcwGat23Iv2ljyvroC7BM=
  on:
    tags: true
    repo: joshmarshall/testnado
